apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: mongodb-uri-sync
  namespace: akv-test
spec:
  vault:
    name: clahan-key-vault-143 # Name of your Azure Key Vault
    object:
      name: MongoDBUri # Name of the AKV object
      type: secret
  output:
    secret:
      name: mongodb-uri-secret # Kubernetes secret name
      dataKey: MongoDBUri # Key to store object value in the Kubernetes secret

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: session-secret-sync
  namespace: akv-test
spec:
  vault:
    name: clahan-key-vault-143
    object:
      name: SESSION-SECRET
      type: secret
  output:
    secret:
      name: session-secret
      dataKey: SESSION-SECRET

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: port-sync
  namespace: akv-test
spec:
  vault:
    name: clahan-key-vault-143
    object:
      name: PORT
      type: secret
  output:
    secret:
      name: port-secret
      dataKey: PORT

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: email-username-sync
  namespace: akv-test
spec:
  vault:
    name: clahan-key-vault-143
    object:
      name: EmailUsername
      type: secret
  output:
    secret:
      name: email-username-secret
      dataKey: EmailUsername

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: email-password-sync
  namespace: akv-test
spec:
  vault:
    name: clahan-key-vault-143
    object:
      name: EmailPassword
      type: secret
  output:
    secret:
      name: email-password-secret
      dataKey: EmailPassword 

