apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: akv-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      initContainers:
      - name: init-front-app
        image: busybox:1.35.0-uclibc
        command: ['sh', '-c', 'echo "Running initialization tasks for the front-end application"; sleep 10;']
      containers:
      - name: usernode-js
        image: saiteja2502/userprofileretail:latest
        ports:
        - containerPort: 3130  # Match your app's port
        env:
        - name: MONGODB-URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri-secret
              key: MongoDBUri
        - name: SESSION-SECRET
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: SESSION-SECRET
        - name: EMAIL-USER
          valueFrom:
            secretKeyRef:
              name: email-username-secret
              key: EmailUsername
        - name: EMAIL-PASS
          valueFrom:
            secretKeyRef:
              name: email-password-secret
              key: EmailPassword
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: port-secret
              key: PORT

